name: Rust Tests

on:
  push:
    paths:
      - "src/**.rs"
      - "tests/**.rs"
      - "examples/**.rs"
      - ".github/**.yml"
      - "Cargo.toml"
      - "Cargo.lock"

jobs:
  test:
    name: Run Tests and Examples
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install OS Dependencies
        run: |
          sudo apt-get update -y

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/
            target/
          key: ${{ runner.os }}-dependencies

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build and Run Tests
        env:
          RUST_BACKTRACE: 1
          RUST_LOG: debug
        run: cargo test --no-fail-fast

      - name: Upload Assets
        uses: EndBug/add-and-commit@v9
        with:
          add: "assets"
          pull: "--rebase --autostash"
