name: Rust Tests

on:
  push:
    paths:
      - "src/**.rs"
      - "tests/**.rs"
      - "examples/**.rs"
      - ".github/**.yml"
      - "Cargo.toml"
      - "Cargo.lock"

jobs:
  test:
    name: Run Tests and Examples
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        example: [iris, mountain_car, cart_pole, mountain_car_compare, cart_pole_compare, unit]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/
            target/
          key: ${{ matrix.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build and Run Example/Test
        if: matrix.example != 'unit'
        env:
          RUST_BACKTRACE: 1
          RUST_LOG: debug
        run: scripts/run_test.sh ${{ matrix.example }}

      - name: Run Unit Tests
        if: matrix.example == 'unit'
        env:
          RUST_BACKTRACE: 1
          RUST_LOG: debug
        run: cargo test --no-fail-fast

      - name: Upload Example Plots
        if: matrix.example != 'unit'
        uses: actions/upload-artifact@v2
        with:
          name: example_plots
          path: assets/plots/examples
          if-no-files-found: error
