name: develop
on:
  push:
    paths:
      - "src/**.rs"
      - "tests/**.rs"
      - "examples/**.rs"
      - ".github/**.yml"
jobs:
  test:
    name: Execute Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: tokusumi/markdown-embed-code@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: mkdir -p ./assets/tests/plots
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          default: true
      - uses: actions-rs/cargo@v1
        with:
          command: test --all-targets
      - uses: actions/upload-artifact@v3
        with:
          name: plots
          path: ./assets/tests/plots
          if-no-files-found: error
      - uses: EndBug/add-and-commit@v9
        with:
          add: "assets/tests/plots"
