name: develop
on:
  push:
    paths:
      - "src/**.rs"
      - "tests/**.rs"
      - "examples/**.rs"
      - ".github/**.yml"
      - "cargo.toml"
jobs:
  embed_code:
    name: Embed Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with: 
          node-version: 14
      - run: npm install -g embedme
      - run: embedme README.md
      - uses: EndBug/add-and-commit@v9
        with:
          add: "README.md"

  test:
    name: Execute Tests
    runs-on: ubuntu-latest
    steps:
      - run: mkdir -p ./assets/tests/plots
      - run: sudo apt install libsdl2-gfx-dev xvfb -y
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          default: true
      - run: xvfb-run cargo run --example=mountain_car
      - uses: actions/upload-artifact@v3
        with:
          name: plots
          path: ./assets/tests/plots
          if-no-files-found: error
      - uses: EndBug/add-and-commit@v9
        with:
          add: "assets/tests/plots"
          pull: "--rebase --autostash"
